version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      # check for updates at 9am UTC
      time: "09:00"
    target-branch: "master"
    # To disable automatic updates for gomod dependencies, set value to zero
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dev QA"
      - "dependency update"
