version: 1
metadata:
  name: funditest
  path: .
structure:
  - folder: funditest # this is the project root directory.
    contains:
      - file: docker-compose
        extension: yml
      - file: README
        extension: md
      - folder: cmd
      - folder: docker-files
      - folder: docs
        contains:
          - file: index
            extension: html
      - folder: features
      - folder: pkg
        contains:
          - folder: app
            contains:
              - file: doc
                extension: go
          - folder: behaviour
          - folder: domain
