version: 1
metadata:
  name: funditest
  path: .
structure:
  - folder: funditest # this is the project root directory.
    contains:
      - file: docker-compose.yml
      - file: README.md
      - folder: cmd
      - folder: docker-files
      - folder: docs
        contains:
          - file: index.html
      - folder: features
      - folder: pkg
        contains:
          - folder: app
            contains:
              - file: doc.go
          - folder: behaviour
          - folder: domain
