name: PR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Linting
        uses: golangci/golangci-lint-action@v2
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install deps
        run: |
          go mod download
          go get -v -u github.com/cucumber/godog/cmd/godog@v0.12.0
      - name: Run unit tests
        run: go test -v -race -tags unit $(for d in internal; do echo ./$d/...; done)
      - name: Run behaviour tests
        run: |
          go install -v ./cmd/fundi
          go test -v -race -tags behaviour ./internal/behaviour
